### ISSUE TITLE
Mac Address Data resets when application restarts

### ISSUE THREAD

**Issue by cseitz** [JMANN240/foodtime#1]
Each time we push a change, Stopher does down to "1 people"

**Comment by cseitz** [comment]
@JMANN240

**Comment by JMANN240** [comment]
Where? On the dev route? main page?

**Comment by cseitz** [comment]
dev page.

**Comment by cseitz** [comment]
There was no .gitignore, which would overwrite json data files each time we deployed.

This issue has been resolved.
